[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "https://www.iptvservice.site/*"
  to = "https://iptvservice.site/:splat"
  status = 301
  force = true

[build]
  publish = "dist"
  command = "npm run build"