[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "https://iptvservice.site/*"
  to = "https://www.iptvservice.site/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://iptvservice.site/*"
  to = "https://www.iptvservice.site/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.iptvservice.site/*"
  to = "https://www.iptvservice.site/:splat"
  status = 301
  force = true

[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "upgrade-insecure-requests"