[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/features/*"
  to = "/features/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/pricing/*"
  to = "/pricing/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/contact/*"
  to = "/contact/:splat"
  status = 301
  force = true

# Redirect removed pages to appropriate destinations
[[redirects]]
  from = "/refund"
  to = "/terms"
  status = 301
  force = true

[[redirects]]
  from = "/setup-guide"
  to = "/features"
  status = 301
  force = true

[[redirects]]
  from = "/troubleshooting"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/faq"
  to = "/features#faq"
  status = 301
  force = true

# Legacy URL redirects
[[redirects]]
  from = "/packages"
  to = "/pricing"
  status = 301
  force = true

[[redirects]]
  from = "/services"
  to = "/features"
  status = 301
  force = true

[[redirects]]
  from = "/support"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/news"
  to = "/blog"
  status = 301
  force = true

# Catch all for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"

# Headers to improve SEO and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    Content-Security-Policy = "upgrade-insecure-requests"

# Cache control for static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"