// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://yfkujybpyjigzcpzrnca.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlma3VqeWJweWppZ3pjcHpybmNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAzNDc3NzQsImV4cCI6MjA0NTkyMzc3NH0.gaw6YBjbmgGXt82gVLzyJQX12jxjveH3JQ7y4BeMCPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);