// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://mxknwykgwqhsedfpkdlt.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14a253eWtnd3Foc2VkZnBrZGx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEwMDg5NzgsImV4cCI6MjA0NjU4NDk3OH0.ZBcxcoL6OojzzA9nCNErLrqnGJCOtrfyhrl7TZdEZFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);